/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.reproducbilityenhancer;

import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Supreme2
 */
public class Panel2 extends javax.swing.JPanel {

    protected MainFrame parentFrame;

    /**
     * Creates new form Panel2
     */
    public Panel2(MainFrame theParentFrame) {
        parentFrame = theParentFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txbPassword = new javax.swing.JTextField();
        txbUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txbNodes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txbStartHost = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txbNumProc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txbLog = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txbSlots = new javax.swing.JTextField();
        txbResultsFile = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        chkResults = new javax.swing.JCheckBox();

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        jLabel2.setText("Username");

        txbNodes.setColumns(20);
        txbNodes.setRows(5);
        jScrollPane1.setViewportView(txbNodes);

        jLabel1.setText("Nodes:");

        jLabel4.setText("Start Host:");

        jLabel5.setText("Num Proc:");

        DefaultCaret caret = (DefaultCaret)txbLog.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        txbLog.setColumns(20);
        txbLog.setRows(5);
        jScrollPane2.setViewportView(txbLog);

        jLabel6.setText("Log:");

        jLabel7.setText("Slots:");

        txbResultsFile.setEnabled(false);

        jLabel23.setText("Name of MPI Results FIle:");

        jLabel22.setText("Fetch MPI Results File?");

        chkResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkResults)
                                        .addGap(0, 149, Short.MAX_VALUE))
                                    .addComponent(txbResultsFile)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(24, 24, 24))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txbUser)
                                    .addComponent(txbPassword)
                                    .addComponent(txbStartHost)
                                    .addComponent(txbNumProc)
                                    .addComponent(txbSlots, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(458, 458, 458))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txbStartHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txbNumProc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txbSlots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkResults)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txbResultsFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            new Thread(new Runnable() {

                @Override
                public void run() {
                    update("Starting");
                    String image = null;
                    String executable = null;
                    String args = null;
                    MPI mpi = null;
                    String[] nodes = null;
                    String host = null;
                    try {
                        String s = new String(Files.readAllBytes(Paths.get("config")), Charset.defaultCharset());
                        String[] config = s.split("\n");
                        image = config[0].substring(config[0].lastIndexOf("%") + 1);
                        executable = config[1].substring(config[1].lastIndexOf("%") + 1);
                        args = config[2].substring(config[2].lastIndexOf("%") + 1);
                        nodes = txbNodes.getText().split("\n");
                        host = txbStartHost.getText();
                        mpi = new MPI(args, txbNumProc.getText(), executable, host, txbUser.getText(), txbPassword.getText(), nodes, image, String.valueOf(txbSlots.getText()));

                    } catch (Exception e) {
                    }

                    mpi.makeHostFile();
                    //Put new host file on head node
                    RemoteServer rs = new RemoteServer(nodes[0], txbUser.getText(), txbPassword.getText());
                    rs.sendFile("hosts", "hosts");

                    //Launch containers on all nodes and set up networking    
                    update("Starting containers on nodes and configuring networking...");
                    mpi.deployContainers(txbLog);

                    //Run MPI
                    update("Running MPI...");
                    String results = mpi.runMPI(txbLog);
                    update(results);

                    //Fetch MPI results from head node
                    if (chkResults.isSelected()) {
                        update("Fetching results file from head node...");
                        mpi.fetch(txbResultsFile.getText());
                    }

                    mpi.removeContainers(txbLog);
                    update("Done!");
                }
            }).start();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkResultsActionPerformed
        if (chkResults.isSelected()) {
            txbResultsFile.setEnabled(true);
        } else {
            txbResultsFile.setEnabled(false);
        }
    }//GEN-LAST:event_chkResultsActionPerformed

    private void update(String content) {
        txbLog.setText(txbLog.getText() + "\n" + content);
        txbLog.update(txbLog.getGraphics());
        txbLog.revalidate();
        txbLog.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkResults;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txbLog;
    private javax.swing.JTextArea txbNodes;
    private javax.swing.JTextField txbNumProc;
    private javax.swing.JTextField txbPassword;
    private javax.swing.JTextField txbResultsFile;
    private javax.swing.JTextField txbSlots;
    private javax.swing.JTextField txbStartHost;
    private javax.swing.JTextField txbUser;
    // End of variables declaration//GEN-END:variables
}
